### PR TITLE
Switch to using HashSet rather than TreeSet internally, so that the i…

### PR DESCRIPTION
**Pull request by cinquin**
…nterval data objects do not need to implement the Comparable interface.

### CODE REVIEW

**Comment by phishman3579** [comment]
@cinquin It doesn't pop out at me looking at the code at this moment but I believe there is an expectation that all data in each interval is in sorted order. If that is not a requirement then you are correct. I'll take a look a little deeper in a day or two.

But thanks for the merge request.

**Comment by cinquin** [comment]
There is a need to order the intervals, but not the objects that are associated with those intervals. In fact the ordering relationship (derived from the implicit requirement that O implement Comparable if it is used in IntervalTree<O extends Object>) is not used by anything other than the TreeSet that I changed to HashSet, as far as I can tell. So overall this change makes the intervals usable with a broader set of objects, at no cost I can discern in correctness or functionality.

**Comment by phishman3579** [comment]
I think you are correct. I don't see anything in the code which requires the data to be order. Let me make the change and make sure the unit tests are passing.

**Comment by phishman3579** [comment]
Actually, now that I look at the original code; it had a problem. O was defined as an Object when it should have been a Comparable<O>.
e.g.
O extends Comparable<O>
instead of
O extends Object

Thanks for the patch, it passes the unit tests. I wish there were more unit tests but it passes the few that are there. I'll apply the merge now.

**Pull request merged**
