### PR TITLE
Added PR template in repo

### PR DESCRIPTION
**Pull request by jsroyal**
Issue fixing #40
@phishman3579 
Please review it and come back. Do you like it?
What are the suggestions?
Is it worth?
I think you got the structure if you want to implement then go for it.

I do have a suggestion can we remove default folder created by IDE because its little bit confused and also giving path code take too much string.

### CODE REVIEW

**Comment by jsroyal** [comment]
Hi! @phishman3579 Please review it and if you want to add more then go ahead.
I do have little bit busy so not able to do it right now but I think you got idea about so  please do it.

**Comment by jsroyal** [comment]
Hello! @phishman3579 
I think I did pretty much good for you and now your turn reviews the work and maybe if you want to appreciate then go for ahead. 
 
Also, I just want to thanks for your open source contribution.
One more thing I want to tell you in this era there is such people who are appreciated.
Did you heard about [CodeCuriosity](https://codecuriosity.org/).This is an organization which thinks like us.
So just go ahead and look at there what they do? Why do they?

**Comment by phishman3579** [comment]
I've integrated this into the repo.

**Comment by jsroyal** [comment]
>I've integrated this into the repo.
Means I did not get it.
Is this means you merge my pull request or I as I given the link of  [CodeCuriosity](https://codecuriosity.org/) integrated?
Have you signup in this org website?
But I checked you haven't  as I can see in the pic.  image 
If not then please do you will get some gift $ from this org as goodie through e-commerce.
If you don't want then just ignore it.

**Comment by phishman3579** [comment]
The README

**Comment by jsroyal** [comment]
Okay. Please merge this one also and delete it.

**Pull request merged**
