### PR TITLE
Modular arithmetic

### PR DESCRIPTION
**Pull request by Dakurels**
Adding, subtracting, multiplying, dividing and power in modular arithmetic.

### CODE REVIEW

**Comment by phishman3579** [comment]
Just wondering why you closed this, I was going to merge it today.

**Comment by Dakurels** [comment]
I closed due to changes by @mciancia - he was writing to me, that I need to create new pull request after the mess he did in repo 😛 But I hope, this is not necessary.

**Comment by phishman3579** [comment]
Can you try to close this pull request, do a 'git pull --rebase', and the submit a new pull request?

**Comment by phishman3579** [comment]
Actually, see this answer. http://stackoverflow.com/questions/9813816/git-pull-after-forced-update

**Comment by phishman3579** [comment]
ok, I merged in the other pull request. Just curios, what did you have to do?

**Comment by Dakurels** [comment]
I closed old repository and created new with this changes. Dirty solution but I don't have time for something more clever :P

**Comment by phishman3579** [comment]
Works for me! Thanks.

**Pull request closed without merging**
