### PR TITLE
Depth First Traversal

### PR DESCRIPTION
**Pull request by jsroyal**
Yes! Pease reviews it.
I'm looking forward to more contribution.
FIxed #39

### CODE REVIEW

**Comment by phishman3579** [comment]
Please add some unit tests (test/com/jwetherell/algorithms/graph) and remove the main() method.

**Comment by jsroyal** [comment]
>unit tests (test/com/jwetherell/algorithms/graph)

Actually, I never write before can you give one example about it.

>remove the main() method.

Why??

**Comment by phishman3579** [comment]
See https://github.com/phishman3579/java-algorithms-implementation/blob/master/test/com/jwetherell/algorithms/graph/test/Graphs.java

Those are all the graph unit tests. 

The main() method isn't needed since this is a library and all uses should use the depthFirstTraversal() method for all their needs.

**Comment by jsroyal** [comment]
Can somebody write my test code?
I do still clear about how to write the test cases for given the above example so, please...

**Comment by phishman3579** [comment]
I've updated your DFS code to use a Graph object and also added a unit test. 
See: https://github.com/phishman3579/java-algorithms-implementation/blob/master/test/com/jwetherell/algorithms/graph/test/DepthFirstTraversalTest.java

**Pull request merged**
